version: '3.8'

services:
  api:
    container_name: api
    restart: unless-stopped
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - ./api/.env
    # environment:
    #   - MONGODB_URL=mongodb://mongo:27017/restAPI
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo
      - redis
    networks:
      - beto

  client:
    container_name: client
    restart: unless-stopped
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/src:/app/src
    depends_on:
      - api
    networks:
      - beto

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - beto

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - beto

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client
    networks:
      - beto

volumes:
  mongodb:
  redis:

networks:
  beto: