# Multi-Stage
# Stage 1: build
FROM node:16-alpine as build

WORKDIR /app

COPY . .

RUN yarn && yarn run build

# Stage 2: prod
FROM node:16-alpine as prod

WORKDIR /app

RUN chown -R node:node /app

USER node

COPY --chown=node:node --from=build /app/dist /app/dist

COPY --chown=node:node --from=build /app/package*.json /app/

RUN yarn install --production --frozen-lockfile

CMD [ "yarn", "start" ]